language: go
go:
  - 1.15.x
os: osx
osx_image: xcode10.2
env:
  global:
    - PKG_CONFIG_PATH=/Users/travis/compiled/lib/pkgconfig
    - HIGHEST_CHAIN_TAG=mainnet

script:
  - set -e
  - git fetch --unshallow --tags
  - ./install_ffmpeg.sh
  - go mod download
  - ./ci_env.sh make livepeer livepeer_cli livepool livepeer_bench livepeer_router
  - source ./ci_env.sh make all
  - ./upload_build.sh
