FROM nvidia/cuda:10.1-base

ENTRYPOINT ["/usr/bin/livepool"]

# this is needed to access GPU inside Docker Swarm
ENV NVIDIA_DRIVER_CAPABILITIES=all

COPY --from=livepool/build:latest /build/livepool /usr/bin/livepool
