name: Docker Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        # Needed for commands that depend on git tags
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set global environment variables
      run: |
        echo "PKG_CONFIG_PATH=/root/compiled/lib/pkgconfig" >> $GITHUB_ENV
        echo "GOPATH=/go" >> $GITHUB_ENV
    - name: DockerHub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASS }}
    - name: Build Linux specific builder container
      run: |
        docker pull livepool/build-platform:latest || echo 'no pre-existing cache found'
        docker build -t livepool/build-platform:latest --cache-from=livepool/build-platform:latest -f docker/Dockerfile.build-linux .
        docker push livepool/build-platform:latest
    - name: Build livepeer in a container shared between Linux and Windows
      run: |
        docker pull livepool/build:latest || echo 'no pre-existing cache found'
        ./ci_env.sh docker build --build-arg BUILD_TAGS -t livepool/build:latest --cache-from=livepool/build:latest -f docker/Dockerfile.build .
        docker push livepool/build:latest
    - name: Build minimal livepeer distributable 
      run: |
        # We publish two tags for each build:
        # livepool/go-livepool:BRANCH_NAME and livepool/go-livepool:VERSION_STRING. Both are useful
        # to pull from in different contexts.
        # Our Docker tag name should be our branch name with just alphanums
        BRANCH_TAG=$(echo $GHA_REF | sed 's/refs\/heads\///' | sed 's/\//-/g' | tr -cd '[:alnum:]_-')
        VERSION_TAG=$(./print_version.sh)
        docker build -t current-build -f docker/Dockerfile.release-linux .
        for TAG in $BRANCH_TAG $VERSION_TAG; do
          docker tag current-build livepool/go-livepool:${TAG}-linux
          docker push livepool/go-livepool:${TAG}-linux
          # Manifest step is optional in case the Windows build hasn't finished yet
          docker manifest create livepool/go-livepool:${TAG} livepool/go-livepool:${TAG}-linux livepool/go-livepool:${TAG}-windows || true
          docker manifest push livepool/go-livepool:${TAG} || true
        done
      env:
        GHA_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref }}
